[package]
name = "kafka-wire-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
proptest = "1.6.0"
proptest-derive = "0.5.1"
testcontainers = { version = "0.23.2", features = ["blocking"] }